# Generated by Django 4.1.7 on 2023-02-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='checkpoint',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('cp_name', models.CharField(max_length=100)),
                ('lora_name', models.CharField(max_length=100)),
                ('link_url', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('trigger_words', models.CharField(max_length=200)),
                ('prompt', models.CharField(max_length=500)),
                ('n_prompt', models.CharField(max_length=500)),
                ('folder', models.CharField(max_length=200)),
                ('sampler', models.CharField(max_length=100)),
                ('steps', models.IntegerField()),
                ('cfg_scale', models.IntegerField()),
            ],
        ),
    ]
